### ISSUE TITLE
Support underscores in identifier without escaping

### ISSUE THREAD

**Issue by krksgbr** [cretz/kastree#14]
I've come across the following issue when using `Writer`:

```kotlin
import kastree.ast.Writer
import kastree.ast.psi.Parser


fun main(args: Array<String>) {
    val source = """
        const val c = FOO_BAR
    """

    val file = Parser.parseFile(source)
    println(Writer.write(file))
}
```

This program will output the following:
```kotlin
const val c = `FOO_BAR`
```

For `c` I'd expect (without the back-ticks):
```kotlin
const val c = FOO_BAR
```

**Comment by cretz** [comment]
Yeah, I intentionally didn't put a bunch of logic here: https://github.com/cretz/kastree/blob/48b004925663943d56af76500d91ee30458143f2/ast/ast-common/src/main/kotlin/kastree/ast/Writer.kt#L601-L603

However, I can easily add an underscore in the middle there.

**Comment by krksgbr** [comment]
I see.
Yeah it would be great if you could add that!
We're working on a tool to generate documentation from kotlin source code using kastree.
While the backticked names work fine, it would be more aesthetically pleasing to not have them in the generated docs.

**Comment by cretz** [comment]
This has been added to master and pushed as `0.3.0-SNAPSHOT` to https://oss.sonatype.org/content/repositories/snapshots. I'll leave this open until I release 0.3.0.

**Comment by krksgbr** [comment]
Awesome, thanks!

**Comment by TAGC** [comment]
Do you have any plans on when you're releasing 0.3.0? This isn't a major bug by any means but this library and KotlinPoet make such an awesome combination that the code that my application generates looks almost hand-written, apart from this one niggling thing.

**Comment by cretz** [comment]
I can do it soon. Won't say tomorrow specifically just in case I get busy, but I'll bump it on my priority list. But you can just set that snapshot repo and use that version in the meantime.

**Comment by cretz** [comment]
Released

**Comment by TAGC** [comment]
Nice one man, thanks.
