### ISSUE TITLE
Parsing annotated method call with trailing closure

### ISSUE THREAD

**Issue by krksgbr** [cretz/kastree#15]
When I annotate a method call with a trailing closure like in the following program:
```kotlin
@Target(AnnotationTarget.EXPRESSION)
@Retention(AnnotationRetention.SOURCE)
annotation class MyAnnotation

fun main(args: Array<String>) {
    class Foo(var value: String = "foo")

    val foo = Foo()

    @MyAnnotation
    foo.apply {

    }
}
```

kastree parses the annotated expression the following way:
```kotlin
Annotated(anns=[AnnotationSet(target=null, anns=[Annotation(names=[MyAnnotation], typeArgs=[], args=[])])], expr=Name(name=foo))
```

Notice how the target of the annotation is just the name of the object on which the call is applied (`expr=Name(name=foo)`), instead of the whole expression including the lambda:  I wonder if this is  intentional and whether there is a way of getting a hold of a node that includes the whole expression.

**Comment by cretz** [comment]
I rely on the official Kotlin parser, so it's likely that they do it this way. You can always use a visitor to find a parent node, but it wasn't worth storing parents directly.

**Comment by krksgbr** [comment]
Alright, I see. I'll try your suggestion. Thanks!
