### ISSUE TITLE
Node class should contain begin/end line/column corresponding to its place in the parsed file

### ISSUE THREAD

**Issue by stephentalley** [cretz/kastree#16]
kastree is a great API, thanks!

It would be nice if it the Node class had the ability to provide the location where that Node's text was found in the source file.  This feature is found most other language parsing APIs I've found.

**Comment by cretz** [comment]
I thought about that but didn't want to clutter up the AST w/ parsing info. My original use case wasn't even for parsing, the parsing bit was just so I could run the compiler corpus to ensure my AST covered everything.

Instead, what I did was make it configurable enough to do this on your own. I added a `tag` on the `Node` which accepts any var. You can extend `Converter` and override `onNode` then assign whatever you want from the Kotlin compiler's `PsiElement` to the tag.

I had a bit of time tonight and threw together an example:

```kotlin
import kastree.ast.Node
import kastree.ast.Visitor
import kastree.ast.psi.Converter
import kastree.ast.psi.Parser
import org.jetbrains.kotlin.com.intellij.psi.PsiElement
import org.jetbrains.kotlin.psi.psiUtil.startOffset

fun main(args: Array<String>) {
    // Example with some code
    val code = """
        class Greeter(val name: String) {
            fun greet() {
                println("Hello, ${'$'}name")
            }
        }

        fun main(args: Array<String>) {
            Greeter(args[0]).greet()
        }
    """.trimIndent()
    // Print the code
    println("CODE:")
    printCodeWithLineNums(code)
    // Parse it with pos vals
    val file = parseCodeWithPos(code)
    // Print the nodes
    println("NODES:")
    printNodesWithPos(file)
}

// Parse the code setting the tag as an int pair of 1-based line to 1-based col
fun parseCodeWithPos(code: String) = Parser(object : Converter() {
    override fun onNode(node: Node, elem: PsiElement) {
        // This is obviously the slow way just as a demonstration
        val line = code.take(elem.startOffset).count { it == '\n' } + 1
        val col = elem.startOffset - code.lastIndexOf('\n', elem.startOffset)
        node.tag = line to col
    }
}).parseFile(code)

fun printCodeWithLineNums(code: String) =
    code.lines().forEachIndexed { index, s -> println((index + 1).toString().padStart(3, '0') + ": $s") }

fun printNodesWithPos(v: Node) = (object : Visitor() {
    var currDepth = 0
    override fun visit(v: Node?, parent: Node) {
        (v?.tag as? Pair<Int, Int>)?.also { (line, col) ->
            println("  ".repeat(currDepth) + "${v::class.simpleName}($line:$col)")
        }
        currDepth++
        super.visit(v, parent)
        currDepth--
    }
}).visit(v)
```

Which, when run gives:

    CODE:
    001: class Greeter(val name: String) {
    002:     fun greet() {
    003:         println("Hello, $name")
    004:     }
    005: }
    006: 
    007: fun main(args: Array<String>) {
    008:     Greeter(args[0]).greet()
    009: }
    NODES:
    File(1:1)
      Structured(1:1)
        PrimaryConstructor(1:14)
          Param(1:15)
            Type(1:25)
              Simple(1:25)
                Piece(1:25)
        Func(2:5)
          Block(2:17)
            Block(2:17)
              Expr(3:9)
                Call(3:9)
                  Name(3:9)
                  ValueArg(3:17)
                    StringTmpl(3:17)
                      Regular(3:18)
                      ShortTmpl(3:25)
      Func(7:1)
        Param(7:10)
          Type(7:16)
            Simple(7:16)
              Piece(7:16)
                Type(7:22)
                  Simple(7:22)
                    Piece(7:22)
        Block(7:31)
          Block(7:31)
            Expr(8:5)
              BinaryOp(8:5)
                Call(8:5)
                  Name(8:5)
                  ValueArg(8:13)
                    ArrayAccess(8:13)
                      Name(8:13)
                Call(8:22)
                  Name(8:22)

Let me know if that helps.

**Comment by stephentalley** [comment]
Wow, this is extremely helpful, thanks!

I wasn't able to figure out where you found the startOffset property; the only PsiElement I could find (https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/PsiElement.java) just defined getStartOffsetInParent() but no getStartOffset().  Maybe it has something to do with the different package names (com.intellij.psi.PsiElement in that repo vs. org.jetbrains.kotlin.com.intellij.psi.PsiElement in kastree)?

In any case, it looks like this sufficiently addresses the need.  Thanks again for taking the time to respond.

**Comment by cretz** [comment]
@stephentalley - No prob. See the import for `org.jetbrains.kotlin.psi.psiUtil.startOffset` which brings in the extension property.

**Comment by stephentalley** [comment]
Of course. 🤦‍♂️ Thanks!

**Comment by stephentalley** [comment]
@cretz - I've adopted much of your code posted above but have noticed that the Converter.onNode hook is never called for Node.Extra.Comment nodes (even though it is for Node.Extra.BlankLines).  For my use case, I need this information for all nodes, comments included.

Attached is a patch that should fix the issue (so simple it didn't seem to merit a fork/pull request).

[kastree-patch.txt](https://github.com/cretz/kastree/files/2697345/kastree-patch.txt)

Thanks!

**Comment by cretz** [comment]
Ah, good catch. I will add that `map` call.

Note, I'm not convinced my "extras" approach is really that great, so if you want more control over the comments you can access the psi stuff yourself on the nodes you want comments for. For example, I post-process some aspects of `startsLine` so you might not be able to trust it.

**Comment by cretz** [comment]
Opened issue #17 to address this.

**Comment by stephentalley** [comment]
> Note, I'm not convinced my "extras" approach is really that great, so if you want more control over the comments you can access the psi stuff yourself on the nodes you want comments for.

TBH it would be nice, at least for my use case, if comments were first-class citizens like every other node.  I can certainly create a Converter.WithExtras instead of just a standard Converter, but I guess I'm still wondering why that wouldn't just be the default behavior of Converter.  Or more specifically, why comments merit special casing in this way.

I'll go ahead and re-close this issue since it is now covered by #17.

**Comment by cretz** [comment]
@stephentalley  - In many cases, the comments and blank line info is just not important to people, just like line numbers aren't. If I could do it without putting it on every object I would. This is the best way I could think of to associate comments and blank lines with nodes without infecting the nodes themselves. It is a bit annoying to use an identity map, but I can't think of a better way. That's why I have the tag and onNode stuff, so you can put whatever you want on any node you want without me forcing that approach on every user of this library.

**Comment by stephentalley** [comment]
@cretz - That makes sense, and since there's a workaround that allows access to those nodes, there's no harm in this approach.  I do like the ability to store whatever I need in the tag.

I wonder though if your concerns about simplicity and others' desires for a fuller AST might be addressed by, say, passing a predicate into the Converter constructor (or Parser.parseFile) indicating whether a given PsiElement/Node should be included in the returned AST.

```
// I don't care about Comments
val file = Parser.parseFile(code) { psiElem ->
    psiElem !is PsiComment
}

// I want the full AST
val file = Parser.parseFile(code) { psiElem ->
    true
}

// or just:
val file = Parser.parseFile(code)
```
Visitors who really want to associate a comment with a Node could then just examine the passed-in parent, look at its comments, and save that info into the node's tag.  That might alleviate the need to maintain a slightly awkward identity map.

Just my $.02.
