### ISSUE TITLE
Escape character fails to be parsed

### ISSUE THREAD

**Issue by KennyTsui** [cretz/kastree#3]
Consider the following file:
```
package com.github.cretz

object StringValues {
    const val NewLine: String = "\n"
}
```
After initial setup:
```
val stringValuesFile = File("src/main/kotlin/com/github/cretz/StringValues.kt")
val stringValuesContent = stringValuesFile.readText().trimIndent()
```

The following code:
```
Parser.parseFile(stringValuesContent)
```
... will throw this exception:
```
ParseError(
    file=KtFile: temp.kt,
    errors=[
        PsiErrorElement:Unexpected token in a string template,
        PsiErrorElement:Expecting '"',
        PsiErrorElement:Expecting member declaration,
        PsiErrorElement:Expecting member declaration
    ]
)
```

However, following the README steps work:
```
val code = """
package com.github.cretz

object StringValues {
    const val NewLine: String = "\n"
}
""".trimIndent()
Parser.parseFile(code)
```

The above code will not throw an exception.

The current work around is to replace the source code's `"\n"` with `"""\n"""` however I believe this is not a suitable long term solution.

**Comment by cretz** [comment]
Investigating...

**Comment by cretz** [comment]
@KennyTsui - I am unable to replicate. If a file-turned-into-string is the exact same as a literal string, why would the results be different? Something else is happening with your code or with your file. Did you do any debugging to see if the results of your file load are not 100% character-for-character the same as the string literal that does work?

**Comment by cretz** [comment]
@KennyTsui - Bump. Curious if you still have any issues here. A parsed string and parsed file-to-string should work the exact same if the bytes in the file are 100% the same. I'll close this if the issue no longer persists...

**Comment by cretz** [comment]
@KennyTsui - I'm closing this due to inability to replicate. If this still persists, please upload code that fails to parse.
