### ISSUE TITLE
Is the official Kotlin parser an LR parser? 

### ISSUE THREAD

**Issue by LifeIsStrange** [cretz/kastree#38]
If so, then it could benefit better syntax errors from this paper https://news.ycombinator.com/item?id=23850718

**Comment by cretz** [comment]
I am unsure, it is maintained by JetBrains in the Kotlin repo and is only referred to by this library. (closing as unrelated, feel free to add comment or re-open if needed)

**Comment by drieks** [comment]
Hi @LifeIsStrange,
IDEA is using a fork of https://www.jflex.de/
