### ISSUE TITLE
Annotation argument names are null

### ISSUE THREAD

**Issue by hamoid** [cretz/kastree#42]
Hi :) I'm working on a project that uses kastree (even if it's no longer maintained) and I was wondering if anyone has ideas about why annotation argument names are null. Maybe my mistake?

This is the annotation class
```
@Target(
    AnnotationTarget.EXPRESSION,
    AnnotationTarget.FUNCTION
)
@Retention(AnnotationRetention.SOURCE)
annotation class ProduceVideo(
    val path: String,
    val length: Double = 10.0,
    val frameRate: Int = 30,
    val multiSample: Int = 0
)
```
And this is what I get when I `println(node.anns)`
```
[AnnotationSet(target=null, 
  anns=[Annotation(names=[ProduceVideo], typeArgs=[], 
  args=[
    ValueArg(name=null, asterisk=false, expr=StringTmpl(elems=[Regular(str=media/filters-201.mp4)], raw=false)),
    ValueArg(name=null, asterisk=false, expr=Const(value=5.0, form=FLOAT))])]), 
    AnnotationSet(target=null, anns=[Annotation(names=[Code], typeArgs=[], args=[])]
)]
```

As you can see the `name` is null. Can @JvmName be of any help?

I tried looking into `convertValueArg` to see if I could obtain the name but it seems to be null there already

```
    open fun convertValueArg(v: KtValueArgument): Node.ValueArg {
        val nn = v.getArgumentName()
        if(nn != null) {
            println("---> ${v.name} ${nn.asName}")
        } else {
            println("---> ${v.name}")
        }
        return Node.ValueArg(
            name = v.getArgumentName()?.asName?.asString(),
            asterisk = v.getSpreadElement() != null,
            expr = convertExpr(v.getArgumentExpression() ?: error("No expr for value arg"))
        ).map(v)
    }
```

edit: just to make it clear, I would like to get the names `path`, `length`, `frameRate` and `multiSample` so I know what the value refers to.

**Comment by cretz** [comment]
I no longer have the time to support this library, sorry. You may find https://github.com/kotlinx/ast or similar to work better.

**Comment by hamoid** [comment]
I understand. Good luck with your current projects! :-)
