### ISSUE TITLE
Potential clarification of repo setup instructions

### ISSUE THREAD

**Issue by TAGC** [cretz/kastree#5]
The current setup instructions state:

> The tests rely on a checked out version of the [Kotlin source repository](https://github.com/JetBrains/kotlin) since it uses the test data there to build a corpus to test against. The path to the base of the repo needs to be set as the `KOTLIN_REPO` environment variable.

However, just checking out the Kotlin repo (on master) and pointing this repo to that isn't sufficient by itself. All the Kastree tests failed until I went and set up the Kotlin repo properly. I think it would be helpful to clarify that after checking out the Kotlin repo, the user should follow their [build setup guidelines](https://github.com/JetBrains/kotlin#build-environment-requirements). I'm not entirely sure it's necessary but I ran `gradle` in the Kotlin project root directory to perform the default build setup tasks (and also `gradle compilerTests` but I quit that 30 minutes in). Perhaps something like:

> The tests rely on a checked out version of the [Kotlin source repository](https://github.com/JetBrains/kotlin) since it uses the test data there to build a corpus to test against. The path to the base of the repo needs to be set as the `KOTLIN_REPO` environment variable, and you should ensure that the Kotlin source repository is properly set up itself by following the build setup instructions in its README and invoking `$ gradle` in its root directory. Once this is done, ...

**Comment by cretz** [comment]
Hrmm, I will have to check. I didn't require that in the past, but the repo may have changed in the meantime.

**Comment by cretz** [comment]
@TAGC - After merging in #6, the tests seem to work just fine. Simple having the latest Kotlin source repo checked out from master, having `KOTLIN_REPO` set to that path, and running the tests seems to work just fine. No steps on the Kotlin repo are required. Can you verify?

**Comment by TAGC** [comment]
I deleted the Kotlin source repo, re-cloned it and tried running `gradle test` again in the kastree repo (with the latest commit from master checked out), and yeah it seems to work fine.
